{
  "cve": "CVE-2014-0472",
  "mitre": {
    "cpes": [],
    "created": "2014-04-23T14:00:00+00:00",
    "description": "The django.core.urlresolvers.reverse function in Django before 1.4.11, 1.5.x before 1.5.6, 1.6.x before 1.6.3, and 1.7.x before 1.7 beta 2 allows remote attackers to import and execute arbitrary Python modules by leveraging a view that constructs URLs using user input and a \"dotted Python path.\"",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2014/0xxx/CVE-2014-0472.json",
    "references": [
      "http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html",
      "http://rhn.redhat.com/errata/RHSA-2014-0456.html",
      "http://rhn.redhat.com/errata/RHSA-2014-0457.html",
      "http://secunia.com/advisories/61281",
      "http://www.debian.org/security/2014/dsa-2934",
      "http://www.ubuntu.com/usn/USN-2169-1",
      "https://www.djangoproject.com/weblog/2014/apr/21/security/"
    ],
    "title": null,
    "updated": "2024-08-06T09:20:17.941000+00:00",
    "vendors": [],
    "weaknesses": []
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.4.1:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.4.2:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.4.3:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.4.4:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.4.5:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.4.6:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.4.7:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.4.8:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.4.9:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.4:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.5.1:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.5.2:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.5.3:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.5.4:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.5.5:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.5:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.6.1:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.6.2:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.6:*:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.7:alpha1:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.7:alpha2:*:*:*:*:*:*",
      "cpe:2.3:a:djangoproject:django:1.7:beta1:*:*:*:*:*:*",
      "cpe:2.3:o:canonical:ubuntu_linux:10.04:-:lts:*:*:*:*:*",
      "cpe:2.3:o:canonical:ubuntu_linux:12.04:-:lts:*:*:*:*:*",
      "cpe:2.3:o:canonical:ubuntu_linux:12.10:*:*:*:*:*:*:*",
      "cpe:2.3:o:canonical:ubuntu_linux:13.10:*:*:*:*:*:*:*",
      "cpe:2.3:o:canonical:ubuntu_linux:14.04:*:*:*:lts:*:*:*"
    ],
    "created": "2014-04-23T15:55:02.923000+00:00",
    "description": "The django.core.urlresolvers.reverse function in Django before 1.4.11, 1.5.x before 1.5.6, 1.6.x before 1.6.3, and 1.7.x before 1.7 beta 2 allows remote attackers to import and execute arbitrary Python modules by leveraging a view that constructs URLs using user input and a \"dotted Python path.\"",
    "metrics": {
      "cvssV2_0": {
        "score": 5.1,
        "vector": "AV:N/AC:H/Au:N/C:P/I:P/A:P"
      },
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2014/CVE-2014-0472.json",
    "references": [
      "http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html",
      "http://rhn.redhat.com/errata/RHSA-2014-0456.html",
      "http://rhn.redhat.com/errata/RHSA-2014-0457.html",
      "http://secunia.com/advisories/61281",
      "http://www.debian.org/security/2014/dsa-2934",
      "http://www.ubuntu.com/usn/USN-2169-1",
      "https://www.djangoproject.com/weblog/2014/apr/21/security/"
    ],
    "title": null,
    "updated": "2017-01-07T02:59:29.123000+00:00",
    "vendors": [
      "canonical",
      "canonical$PRODUCT$ubuntu_linux",
      "djangoproject",
      "djangoproject$PRODUCT$django"
    ],
    "weaknesses": [
      "CWE-94"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:/a:redhat:openstack:3::el6",
        "cpe:/a:redhat:openstack:4::el6",
        "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.4.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.4.2:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.4.3:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.4.4:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.4.5:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.4.6:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.4.7:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.4.8:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.4.9:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.4:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.5.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.5.2:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.5.3:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.5.4:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.5.5:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.5:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.6.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.6.2:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.6:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.7:alpha1:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.7:alpha2:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.7:beta1:*:*:*:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:10.04:-:lts:*:*:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:12.04:-:lts:*:*:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:12.10:*:*:*:*:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:13.10:*:*:*:*:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:14.04:*:*:*:lts:*:*:*"
      ],
      "providers": [
        "nvd",
        "redhat"
      ]
    },
    "created": {
      "data": "2014-04-21T00:00:00+00:00",
      "provider": "redhat"
    },
    "description": {
      "data": "The django.core.urlresolvers.reverse function in Django before 1.4.11, 1.5.x before 1.5.6, 1.6.x before 1.6.3, and 1.7.x before 1.7 beta 2 allows remote attackers to import and execute arbitrary Python modules by leveraging a view that constructs URLs using user input and a \"dotted Python path.\"",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {
          "score": 5.1,
          "vector": "AV:N/AC:H/Au:N/C:P/I:P/A:P"
        },
        "provider": "nvd"
      },
      "cvssV3_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_1": {
        "data": {},
        "provider": null
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": "Moderate",
        "provider": "redhat"
      }
    },
    "references": {
      "data": [
        "http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html",
        "http://rhn.redhat.com/errata/RHSA-2014-0456.html",
        "http://rhn.redhat.com/errata/RHSA-2014-0457.html",
        "http://secunia.com/advisories/61281",
        "http://www.debian.org/security/2014/dsa-2934",
        "http://www.ubuntu.com/usn/USN-2169-1",
        "https://nvd.nist.gov/vuln/detail/CVE-2014-0472",
        "https://www.cve.org/CVERecord?id=CVE-2014-0472",
        "https://www.djangoproject.com/weblog/2014/apr/21/security/"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    },
    "title": {
      "data": "python-django: unexpected code execution using reverse()",
      "provider": "nvd"
    },
    "updated": {
      "data": "2024-08-06T09:20:17.941000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "canonical",
        "canonical$PRODUCT$ubuntu_linux",
        "djangoproject",
        "djangoproject$PRODUCT$django",
        "redhat",
        "redhat$PRODUCT$openstack"
      ],
      "providers": [
        "nvd",
        "redhat"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-94"
      ],
      "providers": [
        "nvd"
      ]
    }
  },
  "redhat": {
    "cpes": [
      "cpe:/a:redhat:openstack:3::el6",
      "cpe:/a:redhat:openstack:4::el6"
    ],
    "created": "2014-04-21T00:00:00+00:00",
    "description": "The django.core.urlresolvers.reverse function in Django before 1.4.11, 1.5.x before 1.5.6, 1.6.x before 1.6.3, and 1.7.x before 1.7 beta 2 allows remote attackers to import and execute arbitrary Python modules by leveraging a view that constructs URLs using user input and a \"dotted Python path.\"",
    "metrics": {
      "cvssV2_0": {
        "score": 4.3,
        "vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N"
      },
      "cvssV3_0": {},
      "cvssV3_1": {},
      "threat_severity": "Moderate"
    },
    "redhat_repo_path": "2014/CVE-2014-0472.json",
    "references": [
      "https://nvd.nist.gov/vuln/detail/CVE-2014-0472",
      "https://www.cve.org/CVERecord?id=CVE-2014-0472"
    ],
    "title": "python-django: unexpected code execution using reverse()",
    "updated": "2014-04-21T00:00:00+00:00",
    "vendors": [
      "redhat",
      "redhat$PRODUCT$openstack"
    ],
    "weaknesses": []
  }
}