{
  "cve": "CVE-2009-5011",
  "mitre": {
    "cpes": [],
    "created": "2010-10-19T19:00:00+00:00",
    "description": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the getpeername function having an ENOTCONN error, a different vulnerability than CVE-2010-3494.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2009/5xxx/CVE-2009-5011.json",
    "references": [
      "http://code.google.com/p/pyftpdlib/issues/detail?id=100",
      "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY",
      "http://code.google.com/p/pyftpdlib/source/detail?r=543",
      "http://code.google.com/p/pyftpdlib/source/diff?spec=svn543&r=543&format=side&path=/trunk/pyftpdlib/ftpserver.py"
    ],
    "title": null,
    "updated": "2024-09-17T02:42:48.968000+00:00",
    "vendors": [],
    "weaknesses": []
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:g.rodola:pyftpdlib:*:*:*:*:*:*:*:*",
      "cpe:2.3:a:g.rodola:pyftpdlib:0.1.1:*:*:*:*:*:*:*",
      "cpe:2.3:a:g.rodola:pyftpdlib:0.1:*:*:*:*:*:*:*",
      "cpe:2.3:a:g.rodola:pyftpdlib:0.2.0:*:*:*:*:*:*:*",
      "cpe:2.3:a:g.rodola:pyftpdlib:0.3.0:*:*:*:*:*:*:*",
      "cpe:2.3:a:g.rodola:pyftpdlib:0.4.0:*:*:*:*:*:*:*",
      "cpe:2.3:a:g.rodola:pyftpdlib:0.5.0:*:*:*:*:*:*:*"
    ],
    "created": "2010-10-19T20:00:03.017000+00:00",
    "description": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the getpeername function having an ENOTCONN error, a different vulnerability than CVE-2010-3494.",
    "metrics": {
      "cvssV2_0": {
        "score": 4.3,
        "vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P"
      },
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2009/CVE-2009-5011.json",
    "references": [
      "http://code.google.com/p/pyftpdlib/issues/detail?id=100",
      "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY",
      "http://code.google.com/p/pyftpdlib/source/detail?r=543",
      "http://code.google.com/p/pyftpdlib/source/diff?spec=svn543&r=543&format=side&path=/trunk/pyftpdlib/ftpserver.py"
    ],
    "title": null,
    "updated": "2010-10-20T04:00:00+00:00",
    "vendors": [
      "g.rodola",
      "g.rodola$PRODUCT$pyftpdlib"
    ],
    "weaknesses": [
      "CWE-362"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:2.3:a:g.rodola:pyftpdlib:*:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.1.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.2.0:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.3.0:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.4.0:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.5.0:*:*:*:*:*:*:*"
      ],
      "providers": [
        "nvd"
      ]
    },
    "created": {
      "data": "2010-10-19T19:00:00+00:00",
      "provider": "mitre"
    },
    "description": {
      "data": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the getpeername function having an ENOTCONN error, a different vulnerability than CVE-2010-3494.",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {
          "score": 4.3,
          "vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P"
        },
        "provider": "nvd"
      },
      "cvssV3_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_1": {
        "data": {},
        "provider": null
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": null,
        "provider": null
      }
    },
    "references": {
      "data": [
        "http://code.google.com/p/pyftpdlib/issues/detail?id=100",
        "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY",
        "http://code.google.com/p/pyftpdlib/source/detail?r=543",
        "http://code.google.com/p/pyftpdlib/source/diff?spec=svn543&r=543&format=side&path=/trunk/pyftpdlib/ftpserver.py"
      ],
      "providers": [
        "mitre",
        "nvd"
      ]
    },
    "title": {
      "data": null,
      "provider": null
    },
    "updated": {
      "data": "2024-09-17T02:42:48.968000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "g.rodola",
        "g.rodola$PRODUCT$pyftpdlib"
      ],
      "providers": [
        "nvd"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-362"
      ],
      "providers": [
        "nvd"
      ]
    }
  }
}