{
  "cve": "CVE-2018-10881",
  "mitre": {
    "cpes": [],
    "created": "2018-07-26T18:00:00+00:00",
    "description": "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause an out-of-bound access in ext4_get_group_info function, a denial of service, and a system crash by mounting and operating on a crafted ext4 filesystem image.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {
        "score": 4.2,
        "vector": "CVSS:3.0/AV:P/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H"
      },
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2018/10xxx/CVE-2018-10881.json",
    "references": [
      "http://patchwork.ozlabs.org/patch/929792/",
      "http://www.securityfocus.com/bid/104901",
      "https://access.redhat.com/errata/RHSA-2018:2948",
      "https://access.redhat.com/errata/RHSA-2018:3083",
      "https://access.redhat.com/errata/RHSA-2018:3096",
      "https://bugzilla.kernel.org/show_bug.cgi?id=200015",
      "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10881",
      "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6e8ab72a812396996035a37e5ca4b3b99b5d214b",
      "https://lists.debian.org/debian-lts-announce/2018/07/msg00020.html",
      "https://usn.ubuntu.com/3752-1/",
      "https://usn.ubuntu.com/3752-2/",
      "https://usn.ubuntu.com/3752-3/",
      "https://usn.ubuntu.com/3753-1/",
      "https://usn.ubuntu.com/3753-2/",
      "https://usn.ubuntu.com/3754-1/"
    ],
    "title": null,
    "updated": "2024-08-05T07:54:34.835000+00:00",
    "vendors": [],
    "weaknesses": [
      "CWE-787"
    ]
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:o:canonical:ubuntu_linux:14.04:*:*:*:lts:*:*:*",
      "cpe:2.3:o:canonical:ubuntu_linux:16.04:*:*:*:lts:*:*:*",
      "cpe:2.3:o:canonical:ubuntu_linux:18.04:*:*:*:lts:*:*:*",
      "cpe:2.3:o:debian:debian_linux:8.0:*:*:*:*:*:*:*",
      "cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*",
      "cpe:2.3:o:redhat:enterprise_linux_desktop:7.0:*:*:*:*:*:*:*",
      "cpe:2.3:o:redhat:enterprise_linux_for_real_time:7.0:*:*:*:*:*:*:*",
      "cpe:2.3:o:redhat:enterprise_linux_for_real_time_for_nfv:7:*:*:*:*:*:*:*",
      "cpe:2.3:o:redhat:enterprise_linux_server:7.0:*:*:*:*:*:*:*",
      "cpe:2.3:o:redhat:enterprise_linux_workstation:7.0:*:*:*:*:*:*:*"
    ],
    "created": "2018-07-26T18:29:00.417000+00:00",
    "description": "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause an out-of-bound access in ext4_get_group_info function, a denial of service, and a system crash by mounting and operating on a crafted ext4 filesystem image.",
    "metrics": {
      "cvssV2_0": {
        "score": 4.9,
        "vector": "AV:L/AC:L/Au:N/C:N/I:N/A:C"
      },
      "cvssV3_0": {
        "score": 5.5,
        "vector": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
      },
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2018/CVE-2018-10881.json",
    "references": [
      "http://patchwork.ozlabs.org/patch/929792/",
      "http://www.securityfocus.com/bid/104901",
      "https://access.redhat.com/errata/RHSA-2018:2948",
      "https://access.redhat.com/errata/RHSA-2018:3083",
      "https://access.redhat.com/errata/RHSA-2018:3096",
      "https://bugzilla.kernel.org/show_bug.cgi?id=200015",
      "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10881",
      "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6e8ab72a812396996035a37e5ca4b3b99b5d214b",
      "https://lists.debian.org/debian-lts-announce/2018/07/msg00020.html",
      "https://usn.ubuntu.com/3752-1/",
      "https://usn.ubuntu.com/3752-2/",
      "https://usn.ubuntu.com/3752-3/",
      "https://usn.ubuntu.com/3753-1/",
      "https://usn.ubuntu.com/3753-2/",
      "https://usn.ubuntu.com/3754-1/"
    ],
    "title": null,
    "updated": "2023-02-12T23:31:40.823000+00:00",
    "vendors": [
      "canonical",
      "canonical$PRODUCT$ubuntu_linux",
      "debian",
      "debian$PRODUCT$debian_linux",
      "linux",
      "linux$PRODUCT$linux_kernel",
      "redhat",
      "redhat$PRODUCT$enterprise_linux_desktop",
      "redhat$PRODUCT$enterprise_linux_for_real_time",
      "redhat$PRODUCT$enterprise_linux_for_real_time_for_nfv",
      "redhat$PRODUCT$enterprise_linux_server",
      "redhat$PRODUCT$enterprise_linux_workstation"
    ],
    "weaknesses": [
      "CWE-119",
      "CWE-787"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:/a:redhat:rhel_extras_rt:7",
        "cpe:/o:redhat:enterprise_linux:7",
        "cpe:2.3:o:canonical:ubuntu_linux:14.04:*:*:*:lts:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:16.04:*:*:*:lts:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:18.04:*:*:*:lts:*:*:*",
        "cpe:2.3:o:debian:debian_linux:8.0:*:*:*:*:*:*:*",
        "cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*",
        "cpe:2.3:o:redhat:enterprise_linux_desktop:7.0:*:*:*:*:*:*:*",
        "cpe:2.3:o:redhat:enterprise_linux_for_real_time:7.0:*:*:*:*:*:*:*",
        "cpe:2.3:o:redhat:enterprise_linux_for_real_time_for_nfv:7:*:*:*:*:*:*:*",
        "cpe:2.3:o:redhat:enterprise_linux_server:7.0:*:*:*:*:*:*:*",
        "cpe:2.3:o:redhat:enterprise_linux_workstation:7.0:*:*:*:*:*:*:*"
      ],
      "providers": [
        "nvd",
        "redhat"
      ]
    },
    "created": {
      "data": "2018-06-10T00:00:00+00:00",
      "provider": "redhat"
    },
    "description": {
      "data": "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause an out-of-bound access in ext4_get_group_info function, a denial of service, and a system crash by mounting and operating on a crafted ext4 filesystem image.",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {
          "score": 4.9,
          "vector": "AV:L/AC:L/Au:N/C:N/I:N/A:C"
        },
        "provider": "nvd"
      },
      "cvssV3_0": {
        "data": {
          "score": 4.2,
          "vector": "CVSS:3.0/AV:P/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H"
        },
        "provider": "mitre"
      },
      "cvssV3_1": {
        "data": {},
        "provider": null
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": "Low",
        "provider": "redhat"
      }
    },
    "references": {
      "data": [
        "http://patchwork.ozlabs.org/patch/929792/",
        "http://www.securityfocus.com/bid/104901",
        "https://access.redhat.com/errata/RHSA-2018:2948",
        "https://access.redhat.com/errata/RHSA-2018:3083",
        "https://access.redhat.com/errata/RHSA-2018:3096",
        "https://bugzilla.kernel.org/show_bug.cgi?id=200015",
        "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10881",
        "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6e8ab72a812396996035a37e5ca4b3b99b5d214b",
        "https://lists.debian.org/debian-lts-announce/2018/07/msg00020.html",
        "https://nvd.nist.gov/vuln/detail/CVE-2018-10881",
        "https://usn.ubuntu.com/3752-1/",
        "https://usn.ubuntu.com/3752-2/",
        "https://usn.ubuntu.com/3752-3/",
        "https://usn.ubuntu.com/3753-1/",
        "https://usn.ubuntu.com/3753-2/",
        "https://usn.ubuntu.com/3754-1/",
        "https://www.cve.org/CVERecord?id=CVE-2018-10881"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    },
    "title": {
      "data": "kernel: out-of-bound access in ext4_get_group_info() when mounting and operating a crafted ext4 image",
      "provider": "nvd"
    },
    "updated": {
      "data": "2024-08-05T07:54:34.835000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "canonical",
        "canonical$PRODUCT$ubuntu_linux",
        "debian",
        "debian$PRODUCT$debian_linux",
        "linux",
        "linux$PRODUCT$linux_kernel",
        "redhat",
        "redhat$PRODUCT$enterprise_linux",
        "redhat$PRODUCT$enterprise_linux_desktop",
        "redhat$PRODUCT$enterprise_linux_for_real_time",
        "redhat$PRODUCT$enterprise_linux_for_real_time_for_nfv",
        "redhat$PRODUCT$enterprise_linux_server",
        "redhat$PRODUCT$enterprise_linux_workstation",
        "redhat$PRODUCT$rhel_extras_rt"
      ],
      "providers": [
        "nvd",
        "redhat"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-119",
        "CWE-787"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    }
  },
  "redhat": {
    "cpes": [
      "cpe:/a:redhat:rhel_extras_rt:7",
      "cpe:/o:redhat:enterprise_linux:7"
    ],
    "created": "2018-06-10T00:00:00+00:00",
    "description": "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause an out-of-bound access in ext4_get_group_info function, a denial of service, and a system crash by mounting and operating on a crafted ext4 filesystem image.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {
        "score": 4.2,
        "vector": "CVSS:3.0/AV:P/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H"
      },
      "cvssV3_1": {},
      "threat_severity": "Low"
    },
    "redhat_repo_path": "2018/CVE-2018-10881.json",
    "references": [
      "https://nvd.nist.gov/vuln/detail/CVE-2018-10881",
      "https://www.cve.org/CVERecord?id=CVE-2018-10881"
    ],
    "title": "kernel: out-of-bound access in ext4_get_group_info() when mounting and operating a crafted ext4 image",
    "updated": "2018-06-10T00:00:00+00:00",
    "vendors": [
      "redhat",
      "redhat$PRODUCT$enterprise_linux",
      "redhat$PRODUCT$rhel_extras_rt"
    ],
    "weaknesses": [
      "CWE-787"
    ]
  }
}