{
  "cve": "CVE-2020-35501",
  "mitre": {
    "cpes": [],
    "created": "2022-03-30T00:00:00+00:00",
    "description": "A flaw was found in the Linux kernels implementation of audit rules, where a syscall can unexpectedly not be correctly not be logged by the audit subsystem",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2020/35xxx/CVE-2020-35501.json",
    "references": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=1908577"
    ],
    "title": null,
    "updated": "2024-08-04T17:02:08.109000+00:00",
    "vendors": [],
    "weaknesses": [
      "CWE-863"
    ]
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*",
      "cpe:2.3:o:redhat:enterprise_linux:7.0:*:*:*:*:*:*:*",
      "cpe:2.3:o:redhat:enterprise_linux:8.0:*:*:*:*:*:*:*"
    ],
    "created": "2022-03-30T16:15:08.673000+00:00",
    "description": "A flaw was found in the Linux kernels implementation of audit rules, where a syscall can unexpectedly not be correctly not be logged by the audit subsystem",
    "metrics": {
      "cvssV2_0": {
        "score": 3.6,
        "vector": "AV:L/AC:L/Au:N/C:P/I:P/A:N"
      },
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 3.4,
        "vector": "CVSS:3.1/AV:L/AC:L/PR:H/UI:N/S:U/C:L/I:L/A:N"
      },
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2020/CVE-2020-35501.json",
    "references": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=1908577"
    ],
    "title": null,
    "updated": "2022-12-02T19:54:37.647000+00:00",
    "vendors": [
      "linux",
      "linux$PRODUCT$linux_kernel",
      "redhat",
      "redhat$PRODUCT$enterprise_linux"
    ],
    "weaknesses": [
      "CWE-863",
      "NVD-CWE-Other"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*",
        "cpe:2.3:o:redhat:enterprise_linux:7.0:*:*:*:*:*:*:*",
        "cpe:2.3:o:redhat:enterprise_linux:8.0:*:*:*:*:*:*:*"
      ],
      "providers": [
        "nvd"
      ]
    },
    "created": {
      "data": "2021-03-05T00:40:00+00:00",
      "provider": "redhat"
    },
    "description": {
      "data": "A flaw was found in the Linux kernels implementation of audit rules, where a syscall can unexpectedly not be correctly not be logged by the audit subsystem",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {
          "score": 3.6,
          "vector": "AV:L/AC:L/Au:N/C:P/I:P/A:N"
        },
        "provider": "nvd"
      },
      "cvssV3_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_1": {
        "data": {
          "score": 3.4,
          "vector": "CVSS:3.1/AV:L/AC:L/PR:H/UI:N/S:U/C:L/I:L/A:N"
        },
        "provider": "nvd"
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": "Low",
        "provider": "redhat"
      }
    },
    "references": {
      "data": [
        "https://bugzilla.redhat.com/show_bug.cgi?id=1908577",
        "https://nvd.nist.gov/vuln/detail/CVE-2020-35501",
        "https://www.cve.org/CVERecord?id=CVE-2020-35501"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    },
    "title": {
      "data": "kernel: audit not logging access to syscall open_by_handle_at for users with CAP_DAC_READ_SEARCH capability",
      "provider": "nvd"
    },
    "updated": {
      "data": "2024-08-04T17:02:08.109000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "linux",
        "linux$PRODUCT$linux_kernel",
        "redhat",
        "redhat$PRODUCT$enterprise_linux"
      ],
      "providers": [
        "nvd"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-863",
        "NVD-CWE-Other"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    }
  },
  "redhat": {
    "cpes": [],
    "created": "2021-03-05T00:40:00+00:00",
    "description": "A flaw was found in the Linux kernels implementation of audit rules, where a syscall can unexpectedly not be correctly not be logged by the audit subsystem",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 3.4,
        "vector": "CVSS:3.1/AV:L/AC:L/PR:H/UI:N/S:U/C:L/I:L/A:N"
      },
      "threat_severity": "Low"
    },
    "redhat_repo_path": "2020/CVE-2020-35501.json",
    "references": [
      "https://nvd.nist.gov/vuln/detail/CVE-2020-35501",
      "https://www.cve.org/CVERecord?id=CVE-2020-35501"
    ],
    "title": "kernel: audit not logging access to syscall open_by_handle_at for users with CAP_DAC_READ_SEARCH capability",
    "updated": "2021-03-05T00:40:00+00:00",
    "vendors": [],
    "weaknesses": [
      "CWE-863"
    ]
  }
}