{
  "cve": "CVE-2022-33124",
  "mitre": {
    "cpes": [],
    "created": "2022-06-22T19:44:19+00:00",
    "description": "AIOHTTP 3.8.1 can report a \"ValueError: Invalid IPv6 URL\" outcome, which can lead to a Denial of Service (DoS). NOTE: multiple third parties dispute this issue because there is no example of a context in which denial of service would occur, and many common contexts have exception handing in the calling application",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2022/33xxx/CVE-2022-33124.json",
    "references": [
      "https://github.com/aio-libs/aiohttp/issues/6772"
    ],
    "title": null,
    "updated": "2024-08-03T08:01:20.340000+00:00",
    "vendors": [],
    "weaknesses": []
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:aiohttp:aiohttp:3.8.1:*:*:*:*:*:*:*"
    ],
    "created": "2022-06-23T17:15:14.877000+00:00",
    "description": "AIOHTTP 3.8.1 can report a \"ValueError: Invalid IPv6 URL\" outcome, which can lead to a Denial of Service (DoS). NOTE: multiple third parties dispute this issue because there is no example of a context in which denial of service would occur, and many common contexts have exception handing in the calling application",
    "metrics": {
      "cvssV2_0": {
        "score": 4.3,
        "vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P"
      },
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 5.5,
        "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
      },
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2022/CVE-2022-33124.json",
    "references": [
      "https://github.com/aio-libs/aiohttp/issues/6772"
    ],
    "title": null,
    "updated": "2024-08-03T08:15:48.317000+00:00",
    "vendors": [
      "aiohttp",
      "aiohttp$PRODUCT$aiohttp"
    ],
    "weaknesses": [
      "NVD-CWE-Other"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:2.3:a:aiohttp:aiohttp:3.8.1:*:*:*:*:*:*:*"
      ],
      "providers": [
        "nvd"
      ]
    },
    "created": {
      "data": "2022-06-22T19:44:19+00:00",
      "provider": "mitre"
    },
    "description": {
      "data": "AIOHTTP 3.8.1 can report a \"ValueError: Invalid IPv6 URL\" outcome, which can lead to a Denial of Service (DoS). NOTE: multiple third parties dispute this issue because there is no example of a context in which denial of service would occur, and many common contexts have exception handing in the calling application",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {
          "score": 4.3,
          "vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P"
        },
        "provider": "nvd"
      },
      "cvssV3_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_1": {
        "data": {
          "score": 5.5,
          "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
        },
        "provider": "nvd"
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": null,
        "provider": "redhat"
      }
    },
    "references": {
      "data": [
        "https://github.com/aio-libs/aiohttp/issues/6772",
        "https://nvd.nist.gov/vuln/detail/CVE-2022-33124",
        "https://www.cve.org/CVERecord?id=CVE-2022-33124"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    },
    "title": {
      "data": "python-aiohttp: invalid IPv6 URL which can lead to a Denial of Service with exception raised",
      "provider": "nvd"
    },
    "updated": {
      "data": "2024-08-03T08:15:48.317000+00:00",
      "provider": "nvd"
    },
    "vendors": {
      "data": [
        "aiohttp",
        "aiohttp$PRODUCT$aiohttp"
      ],
      "providers": [
        "nvd"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-20",
        "NVD-CWE-Other"
      ],
      "providers": [
        "nvd",
        "redhat"
      ]
    }
  },
  "redhat": {
    "cpes": [],
    "created": "2022-06-23T00:00:00+00:00",
    "description": "AIOHTTP 3.8.1 can report a \"ValueError: Invalid IPv6 URL\" outcome, which can lead to a Denial of Service (DoS). NOTE: multiple third parties dispute this issue because there is no example of a context in which denial of service would occur, and many common contexts have exception handing in the calling application",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 0.0,
        "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:N/A:N"
      },
      "threat_severity": null
    },
    "redhat_repo_path": "2022/CVE-2022-33124.json",
    "references": [
      "https://nvd.nist.gov/vuln/detail/CVE-2022-33124",
      "https://www.cve.org/CVERecord?id=CVE-2022-33124"
    ],
    "title": "python-aiohttp: invalid IPv6 URL which can lead to a Denial of Service with exception raised",
    "updated": "2022-06-23T00:00:00+00:00",
    "vendors": [],
    "weaknesses": [
      "CWE-20"
    ]
  }
}