{
  "cve": "CVE-2022-23565",
  "mitre": {
    "cpes": [],
    "created": "2022-02-04T22:32:40+00:00",
    "description": "Tensorflow is an Open Source Machine Learning Framework. An attacker can trigger denial of service via assertion failure by altering a `SavedModel` on disk such that `AttrDef`s of some operation are duplicated. The fix will be included in TensorFlow 2.8.0. We will also cherrypick this commit on TensorFlow 2.7.1, TensorFlow 2.6.3, and TensorFlow 2.5.3, as these are also affected and still in supported range.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 6.5,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
      },
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2022/23xxx/CVE-2022-23565.json",
    "references": [
      "https://github.com/tensorflow/tensorflow/commit/c2b31ff2d3151acb230edc3f5b1832d2c713a9e0",
      "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-4v5p-v5h9-6xjx"
    ],
    "title": "`CHECK`-failures in Tensorflow",
    "updated": "2024-08-03T03:43:46.543000+00:00",
    "vendors": [],
    "weaknesses": [
      "CWE-617"
    ]
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
      "cpe:2.3:a:google:tensorflow:2.7.0:*:*:*:*:*:*:*"
    ],
    "created": "2022-02-04T23:15:14.007000+00:00",
    "description": "Tensorflow is an Open Source Machine Learning Framework. An attacker can trigger denial of service via assertion failure by altering a `SavedModel` on disk such that `AttrDef`s of some operation are duplicated. The fix will be included in TensorFlow 2.8.0. We will also cherrypick this commit on TensorFlow 2.7.1, TensorFlow 2.6.3, and TensorFlow 2.5.3, as these are also affected and still in supported range.",
    "metrics": {
      "cvssV2_0": {
        "score": 4.0,
        "vector": "AV:N/AC:L/Au:S/C:N/I:N/A:P"
      },
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 6.5,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
      },
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2022/CVE-2022-23565.json",
    "references": [
      "https://github.com/tensorflow/tensorflow/commit/c2b31ff2d3151acb230edc3f5b1832d2c713a9e0",
      "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-4v5p-v5h9-6xjx"
    ],
    "title": null,
    "updated": "2022-02-09T17:38:40.633000+00:00",
    "vendors": [
      "google",
      "google$PRODUCT$tensorflow"
    ],
    "weaknesses": [
      "CWE-617"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
        "cpe:2.3:a:google:tensorflow:2.7.0:*:*:*:*:*:*:*"
      ],
      "providers": [
        "nvd"
      ]
    },
    "created": {
      "data": "2022-02-04T22:32:40+00:00",
      "provider": "mitre"
    },
    "description": {
      "data": "Tensorflow is an Open Source Machine Learning Framework. An attacker can trigger denial of service via assertion failure by altering a `SavedModel` on disk such that `AttrDef`s of some operation are duplicated. The fix will be included in TensorFlow 2.8.0. We will also cherrypick this commit on TensorFlow 2.7.1, TensorFlow 2.6.3, and TensorFlow 2.5.3, as these are also affected and still in supported range.",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {
          "score": 4.0,
          "vector": "AV:N/AC:L/Au:S/C:N/I:N/A:P"
        },
        "provider": "nvd"
      },
      "cvssV3_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_1": {
        "data": {
          "score": 6.5,
          "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
        },
        "provider": "mitre"
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": null,
        "provider": null
      }
    },
    "references": {
      "data": [
        "https://github.com/tensorflow/tensorflow/commit/c2b31ff2d3151acb230edc3f5b1832d2c713a9e0",
        "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-4v5p-v5h9-6xjx"
      ],
      "providers": [
        "mitre",
        "nvd"
      ]
    },
    "title": {
      "data": "`CHECK`-failures in Tensorflow",
      "provider": "mitre"
    },
    "updated": {
      "data": "2024-08-03T03:43:46.543000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "google",
        "google$PRODUCT$tensorflow"
      ],
      "providers": [
        "nvd"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-617"
      ],
      "providers": [
        "mitre",
        "nvd"
      ]
    }
  }
}