{
  "cve": "CVE-2021-20274",
  "mitre": {
    "cpes": [],
    "created": "2021-03-09T13:11:46+00:00",
    "description": "A flaw was found in privoxy before 3.0.32. A crash may occur due a NULL-pointer dereference when the socks server misbehaves.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2021/20xxx/CVE-2021-20274.json",
    "references": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=1936662",
      "https://security.gentoo.org/glsa/202107-16",
      "https://www.privoxy.org/announce.txt"
    ],
    "title": null,
    "updated": "2024-08-03T17:37:23.763000+00:00",
    "vendors": [],
    "weaknesses": [
      "CWE-476"
    ]
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:privoxy:privoxy:*:*:*:*:*:*:*:*"
    ],
    "created": "2021-03-09T14:15:12.850000+00:00",
    "description": "A flaw was found in privoxy before 3.0.32. A crash may occur due a NULL-pointer dereference when the socks server misbehaves.",
    "metrics": {
      "cvssV2_0": {
        "score": 5.0,
        "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
      },
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 7.5,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
      },
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2021/CVE-2021-20274.json",
    "references": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=1936662",
      "https://security.gentoo.org/glsa/202107-16",
      "https://www.privoxy.org/announce.txt"
    ],
    "title": null,
    "updated": "2021-12-14T19:58:24.033000+00:00",
    "vendors": [
      "privoxy",
      "privoxy$PRODUCT$privoxy"
    ],
    "weaknesses": [
      "CWE-476"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:2.3:a:privoxy:privoxy:*:*:*:*:*:*:*:*"
      ],
      "providers": [
        "nvd"
      ]
    },
    "created": {
      "data": "2021-03-09T13:11:46+00:00",
      "provider": "mitre"
    },
    "description": {
      "data": "A flaw was found in privoxy before 3.0.32. A crash may occur due a NULL-pointer dereference when the socks server misbehaves.",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {
          "score": 5.0,
          "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
        },
        "provider": "nvd"
      },
      "cvssV3_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_1": {
        "data": {
          "score": 7.5,
          "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
        },
        "provider": "nvd"
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": null,
        "provider": null
      }
    },
    "references": {
      "data": [
        "https://bugzilla.redhat.com/show_bug.cgi?id=1936662",
        "https://security.gentoo.org/glsa/202107-16",
        "https://www.privoxy.org/announce.txt"
      ],
      "providers": [
        "mitre",
        "nvd"
      ]
    },
    "title": {
      "data": null,
      "provider": null
    },
    "updated": {
      "data": "2024-08-03T17:37:23.763000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "privoxy",
        "privoxy$PRODUCT$privoxy"
      ],
      "providers": [
        "nvd"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-476"
      ],
      "providers": [
        "mitre",
        "nvd"
      ]
    }
  }
}